default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myapp_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: myapp_test
  host: db
  username: postgres
  password: password